name: ctest

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  ctest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: with-tpm
            install: sudo apt-get install -y libtpms-dev
            configure_args: ""
          - name: without-tpm
            install: true
            configure_args: -DM33MU_ENABLE_TPM_LIBTPMS=OFF
    name: ${{ matrix.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt-get update
          ${{ matrix.install }}
      - name: Configure
        run: cmake -S . -B build ${{ matrix.configure_args }}
      - name: Build
        run: cmake --build build
      - name: Test
        run: ctest --test-dir build
